name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-18.04
    services:
      tika:
        image: apache/tika:1.26
        ports:
          - 9998:9998
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4

      - name: Git checkout
        uses: actions/checkout@v2
      
      - name: Download dependencies
        run:  go mod download 

      - name: Run the unit tests
        run: go test github.com/yashmeh/Falabella/utils  

      - name: Run the tika integration tests
        run: go test github.com/yashmeh/Falabella/parser   